apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cd-template
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
  - name: git-repo-name
    description: The name of the deployment to be created / patched

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: cd-pipeline-$(tt.params.git-repo-name)-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: shopcarts-pipeline
      params:
      - name: APP_URL
        value: https://shopcarts-alex-s-3-dev.apps.rm2.thpm.p1.openshiftapps.com/
      workspaces:
      - name: pipeline-workspace
        persistentVolumeClaim:
          claimName: pipeline-pvc
