apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: GIT_REPO
      description: Git Repo URL
      type: string
    - name: GIT_BRANCH
      description: Git Branch to be used
      type: string
      default: master
    - name: APP_NAME
      description: Name of the app
      type: string
      default: shopcarts
    - name: IMAGE_NAME
      description: Name of the image
      type: string
      default: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.APP_NAME):latest'
 