apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  description: This pipeline clones tests, lints, builds, and deploys a container to Kubernetes
  workspaces:
    - name: pipeline-workspace
      description: | 
        This workspace contains the cloned repo files, so they can be read by the
        next task.
  params:
    - name: app-name
    - name: build-image
    - name: repo-url
    - name: branch
      default: master
  tasks:
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
      - name: SCRIPT
        value: "oc create deploy $(params.app-name) --image=$(params.build-image)"
      runAfter:
        - build
